# This is used by repo2docker. conda can install all the Jupyter dependencies.
name: jupyterlab-outsource-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab >=1.0.2,<1.1.0a0
  - nodejs >=11,<12
  - python >=3.7,<3.8.0a0
  - python-socketio >=4,<4.1
