#!/usr/bin/env bash
# This is used by repo2docker _after_ environment.yml, but still during the
# docker build, which is simpler than a dedicated Dockerfile
echo "CONDA_PREFIX is $CONDA_PREFIX"

if [ "${NB_UID}not-on-binder" = "not-on-binder" ]; then
  echo "...and that's fine"
else
  if [ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]; then
    echo "...and we set it to ${CONDA_DIR}"
    export CONDA_PREFIX=$CONDA_DIR
  else
    echo "...and that's fine"
  fi
fi

set -ex
jlpm --ignore-optional || jlpm || echo "well, let's try anyway"
jlpm bootstrap
jupyter labextension list || echo "ok"
rm -rf ${CONDA_PREFIX}/share/jupyter/lab
jlpm lab:link
jupyter labextension list
jupyter lab build --dev-build=False --minimize=True --debug
