name: jupyterlab-outsource-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  # run
  - jupyterlab >=3.1.9,<4
  - python >=3.7,<3.10
  # build
  - pip
  - doit
  - nodejs >=14,<15
  - twine
  - wheel
  # lint
  - black
  - isort
  - flake8
  # utest
  - pytest
  - pytest-cov
  # atest
  - firefox
  - geckodriver
  - robotframework-jupyterlibrary
  # demo toys
  - jupyterlab-link-share
  - ipywidgets
